// src/pages/Invite.tsx
import { PrimaryButton, Spinner, TextField } from '@fluentui/react';
import React, { useContext,  useState } from 'react'
import { useAuthState } from 'react-firebase-hooks/auth';
import { useCollectionOnce, useDocumentOnce } from 'react-firebase-hooks/firestore';

import firebase from "firebase/app";
import 'firebase/auth';
import logo from './../assets/logo.jpg'
import { CONG_ID } from '../constants';
import { useQuery } from '../shared/hooks';
import { GlobalContext } from '../store/GlobalState';
import { User } from '../models/user'
import { Permission, Publisher } from '../models/publisher'
import { useHistory } from "react-router-dom";
import * as EmailValidator from 'email-validator';

export default function Invite() {

    
    
    const [password, setPassword] = useState<string>();
    const { auth, firestore } = useContext(GlobalContext);
    const [user] = useAuthState(auth);
    let query = useQuery();
    let history = useHistory();
    const [isDisabled, setIsDisabled] = React.useState(true);
    const [isLoading, setIsLoading] = React.useState(false);
    const oldPublisherDocQuery = firestore.doc(`congregations/${CONG_ID}/publishers/${query.get('pub')}`);
    const oldPublisherPartsCollectionQuery = firestore.collection(`congregations/${CONG_ID}/publishers/${query.get('pub')}/parts`);
    const [oldPublisherDoc, loading] = useDocumentOnce(oldPublisherDocQuery);
    const [oldPublisherPartsCollection] = useCollectionOnce(oldPublisherPartsCollectionQuery);
    const oldPublisher : Publisher = {
        ...oldPublisherDoc?.data()
    }
    const [email, setEmail] = useState(oldPublisher.email);
    const [name, setName] = useState<{ firstName: string, lastName: string }>({
        firstName: oldPublisher?.firstName ?? "",
        lastName: oldPublisher?.lastName ?? ""
    });

    const createUser = async (credential: firebase.auth.UserCredential) : Promise<any> => {
        try {
            const promises : Promise<any>[] = []
            if (!loading) {
                let newPublisher : Publisher = {
                    ...oldPublisherDoc?.data(),
                    uid: credential.user?.uid,
                    isInvited: true
                }
                if (credential && credential.user) {
                    let user: User = {
                        congregation: CONG_ID,
                        email: credential.user.email ?? "",
                        firstName: newPublisher.firstName,
                        lastName: newPublisher.lastName,
                        isEmailVerified: true,
                        loginProvider: credential.additionalUserInfo?.providerId,
                        permissions: [
                            Permission.programs,
                            Permission.publishers,
                            Permission.speakers
                        ],
                        uid: credential.user.uid
                    }

                    promises.push(firestore.doc(`users/${user.uid}`).set(user))
                    promises.push(firestore.doc(`congregations/${CONG_ID}/publishers/${newPublisher.uid}`)
                    .set(newPublisher))
                    if (!oldPublisherPartsCollection?.empty) {
                        oldPublisherPartsCollection?.docs.forEach(part => {
                            promises.push(firestore.doc(`congregations/${CONG_ID}/publishers/${newPublisher.uid}/parts/${part.id}`).set(part.data()))
                            promises.push(firestore.doc(`congregations/${CONG_ID}/publishers/${oldPublisherDoc?.id}/parts/${part.id}`).delete())
                        })
                    }
                    promises.push(oldPublisherDocQuery.delete())
                    return Promise.all(promises)
                }
            }
        } catch (error) { console.log(error) }
    }


    const signUpWithEmailAndPassword = async () => {
        try {
            setIsLoading(true)
                if (password && oldPublisher.email) {
                    const newCredential = await auth.createUserWithEmailAndPassword(oldPublisher.email, password)
                    if (user) {
                        if (newCredential.credential) {
                            const authUser = await user.linkWithCredential(newCredential.credential)
                            createUser(authUser)
                            .then(() => setIsLoading(false))
                            .then(() => history.push('/admin'))
                        }
                    } else {
                        createUser(newCredential)
                            .then(() => setIsLoading(false))
                            .then(() => history.push('/admin'))
                    }
                }
        } catch (error) {
            console.log(error)
        }
    }
    // eslint-disable-next-line
    const signUpWithProvider = async (provider: string) => {
        try {
            const _provider = provider === 'google' ? new firebase.auth.GoogleAuthProvider() : new firebase.auth.OAuthProvider('apple');
                let result = await auth.signInWithPopup(_provider)
                if (result) { 
                    createUser(result)
                    .then(() => history.push('/admin'))
                 }
        } catch (error) {
            console.log(error)
        }
    }


    return (
        <>
        <div className="flex h-screen w-full justify-center items-center">
            <div className="w-96 mx-auto p-10">
                <div className="w-full flex justify-center mb-5">
                    <img src={logo} className="rounded-full w-28 overflow-hidden" alt="logo" />
                </div>
                <h2 className="font-bold text-2xl">SIGNUP</h2>
                <div className="flex justify-start flex-wrap">

                    {/* <button 
                    onClick={() => loginWithProvider('google')}
                    className="inline-flex mt-2 google w-full items-center justify-center p-2">
                        <img src={google} alt="google"/>
                        <span className="ml-2">Login with Google</span>
                    </button>
                    <button 
                    onClick={() => loginWithProvider('apple')}
                    className="inline-flex my-2 bg-black w-full items-center justify-center p-2">
                        <img src={apple} alt="apple"/>
                        <span className="ml-2 text-white">Sign in with Apple</span>
                    </button> */}
                </div>
                {/* <Separator 
                styles={{
                    content: {
                        background: 'inherit'
                    }
                }} className="bg-gray-50">OR</Separator> */}

                    {
                        loading ? <Spinner /> :
                        <div className="mb-3">
                        <TextField
                            defaultValue={oldPublisher.firstName}
                            onChange={(event, value) => {
                                if (value) {
                                    setName({ 
                                        lastName: name?.lastName ?? '',
                                        firstName: value
                                    })
                                    if (value.length === 0) {
                                        setIsDisabled(true)
                                    } 
                                }
                            }}
                            onGetErrorMessage={(value) => {
                                if (value.length > 1) {
                                    return
                                }
                                return 'Please enter First Name'
                            }}
                            label="First Name"
                            type="text"
                            disabled/>
                        <TextField
                            defaultValue={oldPublisher.lastName}
                            disabled
                            onChange={(event, value) => {
                                if (value) {
                                    setName({ 
                                        firstName: name?.firstName ?? '',
                                        lastName: value
                                    })
                                    if (value.length === 0) {
                                        setIsDisabled(true)
                                    }
                                }
                            }}
                            onGetErrorMessage={(value) => {
                                if (value.length > 1) {
                                    return
                                }
                                return 'Please enter Last Name'
                            }} 
                            label="Last Name"
                            type="text"/>
                           <TextField
                            defaultValue={oldPublisher.email}
                            disabled
                            autoComplete={'off'}
                            onChange={(event, value) => {
                                if (value) {
                                    setEmail(value)
                                    if (!EmailValidator.validate(value)) {
                                        setIsDisabled(true)
                                    }
                                }
                            }}
                            onGetErrorMessage={(value) => {
                                if (EmailValidator.validate(value)) {
                                    return
                                }
                                return 'Not a valid email'
                            }} 
                            label="Email"
                            type="email"/>
                        </div>
                    }

                    <TextField
                        defaultValue={password}
                        label="Password"
                        onChange={(event, value) => {
                            if (value) {
                                setPassword(value)
                            } 
                        }}
                        type="password"
                        onGetErrorMessage={(value) => {
                            if (value.length >= 6) {
                                return
                            }
                            return 'Password needs to be at least 6 characters.'
                        }} 
                        required
                        canRevealPassword
                        revealPasswordAriaLabel="Show password"
                    />
                    <TextField
                        label="Confirm Password"
                        required
                        type="password"
                        onChange={(event, value) => {
                            if (value) {
                                if (value === password) {
                                    setIsDisabled(false)
                                } else {
                                    setIsDisabled(true)
                                }
                            }
                        }}
                        onGetErrorMessage={(value) => {
                            if (password === value) {
                                return
                            }
                            return 'Passwords don\'t match'
                        }} 
                        canRevealPassword
                        revealPasswordAriaLabel="Show password"
                    />
                    {
                        isLoading ? <Spinner className="mt-4" label="Creating your account..." labelPosition="right" /> :
                        <PrimaryButton 
                            text="Sign up" 
                            onClick={() => signUpWithEmailAndPassword()}
                            className="mt-5"
                            allowDisabledFocus 
                            disabled={isDisabled}/>
                    }
                    
            </div>
        </div>
        </>
    )
}

// src/app/auth/invite/invite.component.ts
import { Component, OnInit } from '@angular/core';
import { AngularFirestoreDocument } from '@angular/fire/firestore';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import firebase from 'firebase/app';
import { NgForage } from 'ngforage';
import { Permission, Publisher } from 'src/app/models/publisher.model';
import { EmailMessage, User } from 'src/app/models/user.model';
import { Part } from 'src/app/models/wol.model';
import { EmailService } from 'src/app/services/email.service';
import { FireStoreService } from 'src/app/services/fire-store.service';
import { AuthService } from '../auth.service';

@Component({
  selector: 'app-invite',
  templateUrl: './invite.component.html',
  styleUrls: ['./invite.component.scss']
})
export class InviteComponent implements OnInit {

  signUpForm: FormGroup;
  hide = true;
  empty = true;
  emailMessage = false;
  publisher: Publisher;
  path: string;
  permissions: Permission[] = [Permission.view]
  emailCheck: boolean;
  constructor(
     public fb: FormBuilder,
     public auth: AuthService,
     public forage: NgForage,
     public emailService: EmailService,
     public fireStore: FireStoreService,
     public route: ActivatedRoute,
     private router: Router,
  ) { }

  ngOnInit(): void {
    this.signUpForm = this.fb.group({
      firstName: ['', [Validators.minLength(3), Validators.required]],
      lastName: ['', [Validators.minLength(2), Validators.required]],
      email: ['', [Validators.email, Validators.required]],
      password: ['',
         [
            Validators.pattern('^(?=.*[0-9])(?=.*[a-zA-Z])([a-zA-Z0-9]+)$'),
            Validators.minLength(6),
            Validators.maxLength(25)
         ],
      ]
   });
     this.route.queryParams.subscribe(params => {
       this.path = params.cong;
       let uid = params.pub;
       this.fireStore.fireStore.doc<Publisher>(`congregations/${this.path}/publishers/${uid}`).valueChanges().subscribe(publisher => {
         this.publisher = publisher;
        this.email.setValue(publisher.email)
        this.firstName.setValue(publisher.firstName)
        this.lastName.setValue(publisher.lastName)
       })
     })
  }

  get email() {
     return this.signUpForm.get('email');
  }
  get password() {
     return this.signUpForm.get('password');
  }
  get firstName() {
     return this.signUpForm.get('firstName');
  }

  get lastName() {
     return this.signUpForm.get('lastName');
  }

  createUser(credential: firebase.auth.UserCredential) {
    this.forage.clear().then(() => {
 // create user with email and pass
 this.route.queryParams.subscribe(params => {

  let path = params.cong;

    if (credential) {
      this.forage.setItem('user', credential.user);
      // create fireUser
      let user: User = {
        congregation: `congregations/${path}`,
          displayName: `${this.publisher.firstName} ${this.publisher.lastName}`,
          email: this.publisher.email,
          isEmailVerified: false,
          loginProvider: "email",
          permissions: this.permissions,
          uid: credential.user.uid,
          firstName: this.publisher.firstName,
          lastName: this.publisher.lastName,
          photoURL: null
      }


      this.fireStore.create('users', credential.user.uid, user).then(() => {
        // create replacing publisher

        this.forage.setItem('fireUser', user).then(() => {

          let publisher: Publisher = {
            email: this.publisher.email,
            firstName: this.publisher.firstName,
            gender: this.publisher.gender,
            isInvited: true,
            lastName: this.publisher.lastName,
            parts: this.publisher.parts,
            photoURL: this.publisher.photoURL,
            privilege: this.publisher.privilege,
            isReader: false,
            uid: credential.user.uid
          }

          if (this.publisher.parts.length > 0) {
              this.publisher.parts.forEach(part => {
                let document: AngularFirestoreDocument<Part> = this.fireStore.fireStore.doc<Part>(`congregations/${path}/parts/${part.id}`);
                if (part.assignee.uid == this.publisher.uid) {
                  document.update({
                    assignee: publisher
                  })
                  part.assignee = publisher;
                } else if (part.assistant.uid == this.publisher.uid) {
                  document.update({
                    assistant: publisher
                  })
                  part.assistant = publisher;
                }
              })
          }

          this.fireStore.fireStore.doc<Publisher>(`congregations/${path}/publishers/${credential.user.uid}`).set(publisher).then(() => {

            let msg : EmailMessage = {
              from: "Assemblee App <assemblee.app@gmail.com>",
              subject: `New Login`,
              to: "assemblee.app@gmail.com",
              html: `<p><strong>New login</strong></p><p><strong>${this.publisher.lastName} ${this.publisher.firstName}</strong> just logged in as a user.</p><p>Sincerely,<br>Assemblee App</p>`
            }

            this.emailService.sendEmail(msg);

            this.forage.setItem('congregationRef', `congregations/${path}`)
             // delete old publisher
          this.fireStore.delete(`congregations/${path}/publishers/${this.publisher.uid}`)
          }).then(() => this.router.navigateByUrl('/home/dashboard'))
        })
      })
    }
  })
})
  }

  signUp() {
     if (this.signUpForm.valid) {
       this.auth.afAuth.createUserWithEmailAndPassword(this.email.value, this.password.value).then(credential => {
        this.createUser(credential)
       })
     } else {
       console.log(this.signUpForm.status)
     }
  }

  appleSignIn() {
    let provider = new firebase.auth.OAuthProvider('apple.com');
    this.auth.afAuth.signInWithPopup(provider).then(credential => {
      this.createUser(credential)
    })
  }

  googleSignIn() {
    let provider = new firebase.auth.GoogleAuthProvider();
    this.auth.afAuth.signInWithPopup(provider).then(credential => {
      this.createUser(credential)
    })
  }

}

<div class="row vh-100 justify-content-center align-items-center bg-light px-2">
  <div class="col-lg-3 col-md-6 col-sm-10">
    <div class="w-100 d-flex justify-content-center mb-5">
      <img src="assets/images/logo.jpg" class="rounded-circle" style="width: 100px; height: 100px;">
    </div>
    <div class="mb-4">
      <h4 class="font-weight-bold mb-0">Welcome,</h4>
      <span class="h3" *ngIf="publisher">{{ publisher.lastName }} {{ publisher.firstName }}</span>
    </div>

    <div class="d-flex justify-content-start flex-wrap">
      <button class="btn btn-sm d-inline-flex justify-content-center align-items-center google w-100 mb-2" (click)="googleSignIn()">
       <svg-icon src="assets/images/google.svg" [svgStyle]="{ 'height.px': 18, 'marginTop.px': 5, 'marginBottom.px': 5 }"></svg-icon>
       <span class="ms-2 fw-normal">Google</span>
     </button>

      <button class="btn btn-dark btn-sm d-inline-flex justify-content-center align-items-center w-100" (click)="appleSignIn()">
       <svg-icon src="assets/images/apple.svg" [svgStyle]="{ 'height.px': 18, 'marginTop.px': 5, 'marginBottom.px': 5 }"></svg-icon>
        <span class="ms-1 fw-normal">Sign-in with Apple</span>
       </button>
    </div>

    <hr>

    <form [formGroup]="signUpForm">

      <div class="input-group mb-3">
        <input type="text" class="form-control" placeholder="First Name" formControlName="firstName" id="firstName" autocomplete="given-name">
        <input type="text" class="form-control" placeholder="Last Name" formControlName="lastName" id="lastName" autocomplete="family-name">
      </div>

      <div class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input type="email" class="form-control" aria-describedby="emailHelp" formControlName="email"
          placeholder="jose@publisher.com" required autocomplete="email">
      </div>

      <div class="mb-3">
        <label for="password" class="form-label">Password</label>
        <input type="password" class="form-control" [type]="hide ? 'password' : 'text'" [formControl]="password" autocomplete="new-password">
      </div>
      <button type="submit" class="btn btn-primary btn-sm d-inline-flex align-items-center"
        (click)="signUp()"><span>Submit</span></button>
    </form>

  </div>
</div>
